
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from "next";
import "./globals.css";

import { Inter } from 'next/font/google';
import { InitColorSchemeScript } from '@mui/material';
import Header from '@/components/header/Header';
import ReduxProvider from '@/providers/ReduxProvider';
import { SnackbarProvider } from '@/providers/SnackbarProvider';
import ThemeRegistry from '@/providers/ThemeRegistry';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body>
        <InitColorSchemeScript
          attribute="class"
          defaultMode="system"
          modeStorageKey="zaub-color-mode"
        />
        <AppRouterCacheProvider>
          <ReduxProvider>
            <ThemeRegistry>
              <SnackbarProvider>
                <Header />
                {children}
              </SnackbarProvider>
            </ThemeRegistry>
          </ReduxProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
